AI-Hypercomputer/torchprime

- README.md
This is so that if we make the repo public, users don't get confused about what to expect.
> Update README.md to show experimental status

- torchprime/metrics/mfu.py
- torchprime/metrics/tests/test_mfu.py
This change adds MFU calculation functionality. It's not wired up to any trainer in any way because we don't have a standard schema for spelling out the LLM layer shapes etc.
Fixes #39.
> MFU calculator

- .github/workflows/cpu_test.yml
- README.md
- torchprime/experimental/torchax_models/README.md
- torchprime/experimental/torchax_models/llama/model_with_collectives.py
- torchprime/experimental/torchax_models/llama/model_with_scan.py
- torchprime/experimental/torchax_models/run.py
- torchprime/experimental/torchax_models/test/test_llama.py
- torchprime/experimental/torchax_models/tests/test_import_torchax.py
- torchprime/experimental/torchax_models/train.py
- torchprime/launcher/Dockerfile
Find and replace
c.f. https://github.com/pytorch/xla/pull/8599/files
> Rename torch_xla2 to torchax

- .github/workflows/lint.yml
currently the formatter is run again while rendering the error message
> Fix formatter error message

- torchprime/sharding/shard_model.py
- torchprime/sharding/tests/test_shard_model.py
In Hugging Face transformer models, we have been using FSDPv2 [1] and hardcoded `mark_sharding` calls to annotate tensors with sharding constraints. This is not very extensible. FSDPv2 doesn't support 2D sharding, and changing sharding config requires modifying the model code.
This PR introduces the start of a config based model sharder that generalizes to arbitrary sharding schemes supported by GSPMD, e.g. 2D FSDP+TP sharding, expert parallelism, etc. It adds a `shard_model_from_config` function that can take a vanilla single-device PyTorch model, then replace the weights and activations with sharded versions, without code change.
The user can specify the names of weights to shard and their partition spec. They can also shard certain activations by specifying the names of the `nn.Module` …
> Start of a generic config based model sharder

- torchprime/torch_xla_models/train.py
Resolves https://github.com/AI-Hypercomputer/torchprime/issues/92
> Fix multipod dataloader sharding

- torchprime/rope/rope.py
- torchprime/tests/test_rope.py
This rope impl supports the OG rope and the scaling used in Llama 3.1
> Add a common rope impl

- torchprime/hf_models/configs/default.yaml
- torchprime/hf_models/configs/model/llama-3/config_405b.json
- torchprime/hf_models/train.py
- torchprime/launcher/Dockerfile
Added a Llama 3.1 405B configuration.
Also fixed some comments in the config yaml.
In particular for per_device_train_batch_size, I based the comment on http://shortn/_SR8wqscDlo.
Also changes Dockerfile to install all transformer deps, because the local_transformer may be newer than our transformer dependency. In that case it may require a newer dependency such as tokenizers==0.20 instead of tokenizers==0.19.
> Update HF runner configs

- .github/workflows/cpu_test.yml
- torchprime/launcher/Dockerfile
Fixes https://github.com/AI-Hypercomputer/torchprime/issues/119 (I checked the Llama and Mixtral running time in this PR)
> Update torch_xla pin to 20250227

- .gitignore
- README.md
- torchprime/launcher/Dockerfile
- torchprime/launcher/buildpush.py
- torchprime/launcher/cli.py
Support install local torch/torch_xla wheel placed under local_dist/ folder
> Support torch/torch_xla wheel locally

- README.md
- torchprime/experimental/torchax_models/README.md
- torchprime/hf_models/README.md
- torchprime/torch_xla_models/README.md
The main change is the addition of a "Model Status" table in the README.md. Because it's good to show how to run a specific model if it's been optimized, I then added recipes for each model and linked them.
I'm also proposing these high level stages for supporting a model:
- **TODO**: We need to implement the model.
- **Implemented**: The model runs either a training or an inference step.
- **Optimized**: We found the best scaling configuration for the model on one or
more hardware. One-off performance data is available.
- **Convergence**: We tested that the training loss converges to a reasonable
value.
- **Production**: Not only is the model optimized and converges, its performance
is also continuously monitored. This is a good state for using the model in
production.
> Document model status

- .github/workflows/cpu_test.yml
- torchprime/launcher/Dockerfile
To pick up changes like placeholder tensor.
> Update torch_xla docker pin to 20250307

- torchprime/sharding/shard_model.py
We replace `xs.mark_sharding` with `MarkShardingFunction` which shards
gradient too. This should make GSPMD much more robust.
> Shard both forward and backwards

- .github/workflows/cpu_test.yml
- torchprime/launcher/Dockerfile
Update nightly build to unblock https://github.com/AI-Hypercomputer/torchprime/pull/145.
> update docker to 03/12

- .github/workflows/cpu_test.yml
- .github/workflows/e2e_test.yml
- README.md
- torchprime/launcher/Dockerfile
- torchprime/launcher/cli.py
This can catch MegaScale related regressions.
Part of https://github.com/AI-Hypercomputer/torchprime/issues/66.
> Add a multi-slice E2E test and update torch_xla pin to 20250313

- torchprime/launcher/cli.py
This should make the flag more apparent during error cases
> Add error when using incorect workload name pointing to "--name" flag

- pyproject.toml
- torchprime/experimental/torchax_models/splash_attn.py
- torchprime/launcher/cli.py
- torchprime/launcher/thunk.py
- torchprime/mesh/custom_mesh.py
- torchprime/metrics/mfu.py
- torchprime/sharding/shard_model.py
- torchprime/sharding/tests/test_shard_model.py
- torchprime/torch_xla_models/attention.py
- torchprime/torch_xla_models/experimental/custom_kernel.py
- torchprime/torch_xla_models/topology.py
- torchprime/torch_xla_models/train.py
This might help get rid of a weird incompatibility where vscode ruff plugin formatting disagrees with CLI ruff formatting
> Bump ruff to 0.11.4

- torchprime/torch_xla_models/configs/model/llama-3.1-70b.yaml
Add the llama3.1 70B config, will update the performance number next.
Config is based on https://huggingface.co/meta-llama/Llama-3.1-70B/blob/main/config.json.
> add llama3.1 70B config

- docs/sharding.md
Follow up to https://github.com/AI-Hypercomputer/torchprime/pull/212
> Address docs feedback

- README.md
- torchprime/torch_xla_models/README.md
Re-submitting request from local branch
> Updating installation steps for to TPU and torchprime

- docs/README.md
- docs/metrics.md
- torchprime/metrics/metrics.py
Explain how the step time is computed currently in torchprime.
> Document the current metrics

- .dockerignore
- .gitignore
- Ignore ruff cache
- Add a `.gitkeep` file to the various useful folders that are otherwise only created manually
> Improve ignore files

- torchprime/launcher/buildpush.py
- torchprime/launcher/cli.py
- torchprime/launcher/util.py
Teaches the `docker-run` command to use `sudo` if needed.
> Support sudoless/sudo docker everywhere

- torchprime/torch_xla_models/llama4/model.py
- torchprime/torch_xla_models/tests/test_llama4.py
The should be sufficient to make llama4 training to work
> Replacing torch.polar math by sin/cos in rope layer

- .github/workflows/reusable_e2e_check.yml
- docs/contributor/README.md
- e2e_testing/README.md
- e2e_testing/create-e2e-cluster.sh
- torchprime/launcher/cli.py
Also handle cases in the E2E test where the cluster and the submitting service account are in different GCP projects.
> Update XPK cluster documentation

- torchprime/hf_models/README.md
I was going to add them to https://github.com/AI-Hypercomputer/torchprime/pull/257, but that PR got accidentally auto-merged.
> Document Hugging Face model selection and sharding

- torchprime/data/__init__.py
- torchprime/data/dataset.py
- torchprime/data/sft_dataset.py
- torchprime/tests/test_sft_dataset.py
- torchprime/torch_xla_models/README.md
- torchprime/torch_xla_models/configs/dataset/wikitext.yaml
- torchprime/torch_xla_models/train.py
Add SFT dataset builder and extensive unit tests. Support for
- chat and prompt-completion format
- different loss computing approach
- different truncation logic
- packing
> Add data processing pipeline for SFT

- e2e_testing/step_time_bounds.yaml
- Press "Run workflow" button many times
- Run `e2e_testing/update_step_time.py --limit 3000 --start-time '10 days ago'`
> Refine E2E timing from 2554 runs

- torchprime/torch_xla_models/tests/test_trainer.py
Seen in HEAD: https://github.com/AI-Hypercomputer/torchprime/actions/runs/15645385072/job/44081810123
The Dataset is meant to produce CPU tensors, that are later uploaded to the XLA device. Producing XLA tensors causes weird breakages in the framework
TESTED: `pytest torchprime/torch_xla_models/tests/test_trainer.py --count 100 -k test_profiler_trace`
> Fix CPU flake

- torchprime/data/sft_dataset.py
- torchprime/tests/test_sft_dataset.py
Otherwise the SFT-ed model with prompt-completion format data does not know when to stop.
> Always add EoS token for data processing pipeline

- torchprime/torch_xla_models/tests/test_trainer.py
- torchprime/torch_xla_models/trainer/base_trainer.py
this does not test convergence of any model on adamw - that will be for a future PR.
> enable adamw

- .github/workflows/cpu_test.yml
- pyproject.toml
- torchprime/launcher/Dockerfile
- torchprime/launcher/buildpush.py
This is currently causing issues on PyTorchXLA testing. See https://github.com/AI-Hypercomputer/torchprime/actions/runs/16307250134/job/46055848143 and https://github.com/pytorch/xla/issues/9466#issuecomment-3079463010.
> Update torchprime to Python 3.12

- .github/workflows/e2e_test.yml
Not really a fix of this issue #360, but at least e2e test can pass with this config.
> Fix deepseek e2e test

- torchprime/torch_xla_models/tests/test_trainer.py
I encountered a runtime error while running the `test_trainer.py` test.
Environment:
- TPU VM: v6e-8
- Python 3.11
- torch 2.9.0.dev20250825+cpu
- torch-xla 2.9.0+git8243a25
Test command:
```
pytest -v torchprime/torch_xla_models/tests/test_trainer.py
```
Error:
```
============================================================== FAILURES ==============================================================
______________________________________________________ test_trainer_train_loop _______________________________________________________
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7bfab56e8e50>
dummy_config = {'model': {'pure_modules': [], 'remat': {'activation_checkpoint_layers': [], 'optimization_barrier_layers': [], 'scan_...tep': -1, 'profile_dir': '/tmp/profile', 'ici_mesh': …
```
> Fix test_trainer test

- torchprime/torch_xla_models/tests/test_topology.py
I encountered an AssertionError while running the `test_topology.py` test.
Environment:
- TPU VM: v6e-8
- Python 3.11
- torch 2.9.0.dev20250825+cpu
- torch-xla 2.9.0+git8243a25
Test command:
```
pytest -v torchprime/torch_xla_models/tests/test_topology.py
```
Error:
```
torchprime/torch_xla_models/tests/test_topology.py:70: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
torchprime/torch_xla_models/topology.py:93: in get_mesh
return xs.Mesh(devices, mesh_shape, ("data", "fsdp", "tensor", "expert", "context"))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <torch_xla.distributed.spmd.xla_sharding.Mesh object …
```
> Fix test_topology test

- .github/workflows/e2e_test.yml
- e2e_testing/step_time_bounds.yaml
- e2e_testing/update_step_time.py
Ran below command to update step time bound. (Refer: e2e_testing/README.md)
```
python e2e_testing/update_step_time.py     --start-time "2 days ago"
```
> Update step time bounds
