.github/workflows/cpu_test.yml
README.md
pyproject.toml
torchprime/launcher/cli.py

With this change, we can run:
- `tp -i test ...` to run some unit tests
- `tp -i run ...` to run a distributed SPMD command
And the script will monitor the filesystem for changes. It will re-trigger the command again whenever one changes a file, leading to an ergonomic dev/test cycle.
I also found some flags to make the CPU checks faster.
Tested: `tp -i test torchprime/torch_xla_models` to repeatedly run the torch_xla model tests upon edit.

Add a `tp -i` for interactive workflows

---

torchprime/launcher/Dockerfile

This is an optimization. Previously, if I change any file in the docker context (e.g. any python file), then all packages are reinstalled, resulting in a big container layer that's slow to push and pull.
Now if I change a python file, that file will simply be copied into the last docker layer. No more `pip install -e .` thanks to the docker cache.
Addresses a point in
https://github.com/AI-Hypercomputer/torchprime/issues/33.

[docker] Only run `pip install -e .` when changing pyproject.toml

---

README.md
pyproject.toml
torchprime/experimental/torchax_models/README.md
torchprime/experimental/torchax_models/configs/default.yaml
torchprime/experimental/torchax_models/llama/model_with_scan.py
torchprime/experimental/torchax_models/run.py
torchprime/torch_xla_models/configs/default.yaml
torchprime/torch_xla_models/train.py

Since torch_xla uses hydra, the CLI for setting profile dir changed slightly. In order to profile torchax training, we refactor both to use hydra and the same config name for setting profile dir.
I didn't do that in this PR, but it will be simpler to extend the torchax trainer to train both llama and mixtral via configs later.
Tested:
```
python3 torchprime/experimental/torchax_models/run.py global_batch_size=16
tp run torchprime/experimental/torchax_models/run.py \
global_batch_size=256 \
model_type=405B \
seqlen=8192 \
use_custom_offload=True \
use_custom_mesh=True \
model_impl=scan \
tp=4 \
unroll_layers=1
```

Fix profiling of torchax models

---

torchprime/launcher/cli.py
torchprime/launcher/doctor.py

Add the checking for the specified XPK clusters. Previously if users made a mistake in specify cluster name/zone/project, it will only error out after finish building the XPK docker image.
Improved terminal output:
```
$ tp use     --cluster $XPK_CLUSTER_NAME     --project tpu-pytorch     --zone us-east1-b     --num-slices 1     --tpu-type v6e-256     --artifact-dir gs://piz/torc
hprime/llama3/performance/
Activating gcloud config...
Written config .config/default.toml
Checking environment...
Check that docker is installed... ✅
Check that gcloud is logged in... ✅
Check that docker config contains gcr.io credential helper... ✅
Check that the gcloud account can access the gcr.io artifact registry... ✅
Check that kubectl is installed... ✅
Check that gke-gcloud-auth-plugin is installed... ✅ …
```

Improve `tp doctor` checking for cluster existance

---

torchprime/launcher/Dockerfile

Without this, workload crashes on trillium pods
We should undo this when https://github.com/pytorch/xla/issues/8683 is fixed

Temporarily pin Docker base image to 2.6 stable

---

torchprime/sharding/shard_model.py
torchprime/sharding/tests/test_shard_model.py

Fixes #86 and #83.
Unfortunately I can't get torch_xla to conjure up multiple CPU devices for SPMD testing (see bug linked in test) so at this moment there's only a test that someone can locally run on their TPU VM, until #32 is solved.

Add torch_xla and torchax specific sharder

---

torchprime/sharding/shard_model.py
torchprime/sharding/tests/test_shard_model.py
torchprime/torch_xla_models/configs/model/llama-3-8b.yaml
torchprime/torch_xla_models/configs/model/mixtral-8x7b.yaml
torchprime/torch_xla_models/configs/model/scaling/llama-fsdp.yaml
torchprime/torch_xla_models/configs/model/scaling/mixtral-fsdp.yaml
torchprime/torch_xla_models/llama/model.py
torchprime/torch_xla_models/loss.py
torchprime/torch_xla_models/mixtral/model.py
torchprime/torch_xla_models/tests/test_spmd.py
torchprime/torch_xla_models/train.py

This PR replaces FSDPv2 and hardcoded sharding specs with sharding config files.
Tests:
- Added a test that compares FSDPv2 and config based sharder numerics and sharding specs for a 2 layer Llama and 2 layer Mixtral.
- I compared the loss curve and running time for Llama on v6e-8, and Mixtral on v6e-8.
- I also compared them on a Trillium pod on xpk.
Llama FSDPv2:
```
- Step: 0, loss: 12.5718, trace time: 134588.13 ms
- Step: 10, loss: 10.9212, trace time: 878.29 ms
- Step: 20, loss: 9.1416, trace time: 880.09 ms
- Step: 30, loss: 8.2824, trace time: 878.94 ms
- Step: 40, loss: 7.0730, trace time: 883.22 ms
- Step: 50, loss: 6.8937, trace time: 862.05 ms
- Step: 60, loss: 6.9061, trace time: 857.86 ms
- Step: 70, loss: 6.8793, trace time: 874.83 ms
- Step: 80, loss: 6.8040, trace time: …
```

torch_xla trainer uses sharding config

---

.dockerignore
.github/actions/e2e-setup/action.yml
.github/workflows/cpu_test.yml
.github/workflows/e2e_test.yml
.github/workflows/reusable_e2e_check.yml
.gitignore
e2e_testing/README.md
e2e_testing/check_logs.py
e2e_testing/check_profile.py
e2e_testing/gen_name.py
torchprime/launcher/Dockerfile
torchprime/launcher/cli.py
torchprime/launcher/thunk.py

Fixes https://github.com/AI-Hypercomputer/torchprime/issues/52
The workflows in [e2e_test.yml][e2e-test] does a few things:
- Set up `gcloud` credentials from a Service Account key managed in repo secrets.
- Install `torchprime`.
- Test `tp use` and point it to an XPK cluster hosted internally.
- Test `tp run` on a few models.
After kicking off the training of some models, it starts a parallel job for each
model, and runs a few checks. This is implemented in
[reusable_e2e_check.yml][e2e-check]:
- Stream the logs.
- Check workload exit code.
- Check for specific log strings that indicate training success.
- Check that there is a profile `.pb` file.
[e2e-test]: https://github.com/AI-Hypercomputer/torchprime/pull/100/files#diff-a7287cabb55032a1b0277a08d47a1c867352ff9066be89908f0b119f5aa71463 …

End-to-end tests for torch_xla llama and mixtral

---

.gitignore
README.md
pyproject.toml
torchprime/hf_models/configs/default.yaml
torchprime/launcher/Dockerfile

Previously we clone transformers/ under torchprime in order to run huggingface models. This caused the issue that python files who `import transformers` will consider transformers as the one from local folder.
We renaming the `transformers` --> `local_transformers` so that it won't conflict with the package naming.

rename transformers folder to avoid naming conflit with package

---

pyproject.toml
torchprime/rope/rope.py
torchprime/torch_xla_models/configs/model/llama-3.1-405b.yaml
torchprime/torch_xla_models/configs/model/scaling/llama-fsdp-tp.yaml
torchprime/torch_xla_models/llama/model.py
torchprime/torch_xla_models/tests/test_llama.py
torchprime/torch_xla_models/tests/test_topology.py
torchprime/torch_xla_models/topology.py
torchprime/torch_xla_models/train.py

Adds Llama 3.1 405B single pod support for torch_xla.
In order to train 405B on a Trillium pod, we need 64 FSDP by 4 TP
sharding. I added a `llama-fsdp-tp` scaling config that expresses the 2D
sharding configuration and we can also use that for other llama models.
This trains performantly on 1 Trillium pod. The step time was 27.395s
(see http://shortn/_fkc7ggB8PE), which is on par with the
Huggingface result (27.395s).
Longer run over 500 steps: http://shortn/_wyNRllBbOA
Tested: `tp run torchprime/torch_xla_models/train.py model=llama-3.1-405b global_batch_size=64 mesh.fsdp=64 mesh.tensor=4 dataset_config_name=wikitext-103-raw-v1 profile_step=15 profile_duration=100000 max_steps=500 logging_steps=10`

Initial Llama 3.1 405B support

---

torchprime/torch_xla_models/README.md
torchprime/torch_xla_models/configs/model/scaling/llama-fsdp-tp.yaml
torchprime/torch_xla_models/train.py

Fixes https://github.com/AI-Hypercomputer/torchprime/issues/139.
Previously, the batch and sequence dimensions are always squished together by nn.Linear, losing some sharding annotations. This is now no longer the case.
As another proof that the sharding propagation got more sensible, I tried sharding the q/k/v proj activations explicitly:
```
model.layers.*.self_attn.q_proj: [fsdp, null, tensor]
model.layers.*.self_attn.k_proj: [fsdp, null, tensor]
model.layers.*.self_attn.v_proj: [fsdp, null, tensor]
model.layers.*.self_attn.o_proj: [fsdp, null, tensor]
```
Without replacing nn.Linear with einsum, this actually _decreases_ MFU. Now this keeps MFU unchanged in Llama 3.0 8B which is the expected behavior.
When I tested on Llama 3.1 405B on one pod, the MFU increased to 29.91% because this …

Replace nn.Linear with einsum in the model

---

torchprime/torch_xla_models/offloading.py
torchprime/torch_xla_models/remat_all.py
torchprime/torch_xla_models/tests/test_offloading.py
torchprime/torch_xla_models/tests/test_remat_all.py

The main purpose is to be able to add activation checkpointing and host offloading of layer inputs to scan, which will be added later. Specifically, `torch_xla` scan takes a FX graph partitioner, so we can pass `remat_all` to implement full activation checkpointing, and pass `remat_all_and_offload_these_inputs` to implement "full activation checkpointing + offloading some input tensors to host".
And add unit tests that they work as intended.

Introduce two FX graph partitioners: remat_all and remat_all_and_offload_these_inputs

---

README.md
torchprime/launcher/buildpush.py
torchprime/launcher/cli.py

Support to run train.py locally:
```
tp dbrun --use-hf torchprime/hf_models/train.py # huggingface run
```
Or 
```
tp dbrun  torchprime/torch_xla_models/train.py 
```
This makes it easier to debug model code.
Currently it is still using the torch_xla from the base docker image. In the future, we may want to give the option to run with local build torch_xla.

Support run trainer locally

---

README.md
torchprime/layers/sequential.py
torchprime/torch_xla_models/llama/model.py
torchprime/torch_xla_models/mixtral/model.py
torchprime/torch_xla_models/scan_layers.py
torchprime/torch_xla_models/tests/test_llama.py
torchprime/torch_xla_models/tests/test_mixtral.py

We replace the `for` loop in both Llama and Mixtral with an equivalent `HomogenousSequential` layer, which can be either run a for loop or use `torch_xla`'s scan operator. This is a clean-ish way to turn scan on/off without cluttering the modeling code.
I also adjusted Mixtral slightly so that we can even run `scan` in Mixtral with its static MoE implementation. In order to integrate with scan, we need to refactor the Mixtral decoder for loop into a format where results from the previous iteration feed into the next iteration. Scanning over GMM on the other hand won't work until GMM forward/backward is wrapped in a custom op similar to https://github.com/pytorch/xla/pull/8654.
Cleanup the README that got jumbled in https://github.com/AI-Hypercomputer/torchprime/pull/111 while I'm here. …

Make models amenable to scan

---

torchprime/torch_xla_models/configs/model/mixtral-8x7b.yaml
torchprime/torch_xla_models/mixtral/model.py

Step time with the current implementation: 8.931s with the command:
```
tp run torchprime/torch_xla_models/train.py global_batch_size=2048 max_steps=50 block_size=4096 profile_step=10 ici_mesh.fsdp=256 dataset_config_name=wikitext-103-raw-v1
```
Run logs: https://cloudlogging.app.goo.gl/e56NzVU29jv5D9Ef9
The best huggingface step time that I got was 8.691s. I think that the difference could be due to different libtpu versions and I don't think it's worth spending additional time to optimize further.

Update mixtral implementation to dropping

---

.github/workflows/cpu_test.yml
torchprime/launcher/Dockerfile
torchprime/torch_xla_models/attention.py
torchprime/torch_xla_models/experimental/custom_kernel.py
torchprime/torch_xla_models/llama/model.py
torchprime/torch_xla_models/mixtral/model.py
torchprime/torch_xla_models/offloading.py
torchprime/torch_xla_models/remat_all.py

1. Extract out the attention module into a separate file.
2. Clean up the splash attention kernel `call_jax`.
Fixes https://github.com/AI-Hypercomputer/torchprime/issues/154.

Refactor attention module

---

pyproject.toml

Looks like installing 2.18 will forcefully downgrade jax to 0.53, which nullifies the recent libtpu pin update.
TEST: llama 405b 1 pod profile: http://shortn/_BlyRalgivF, logs: http://shortn/_lCU1qeMBjz

Bump tensorflow to 2.19

---

.github/workflows/e2e_test.yml

Increase the allowed jitter from 1% of step time on both sides to 1.5% of step time. This is because one test immediately failed [1] when we turned on the step time checking.
[1]: https://github.com/AI-Hypercomputer/torchprime/actions/runs/14457079479/job/40542983084

Relax the E2E step time bounds a bit

---

README.md
docs/README.md
docs/contributor/README.md
docs/sharding.md
torchprime/sharding/shard_model.py

[See rendered markdown](https://github.com/AI-Hypercomputer/torchprime/blob/yifeit/docs-1/docs/sharding.md)
I also moved some workflows that are less likely to be used by the end-user into the contributor guide, which also lives in `docs/` now.
I also added some placeholders for other useful docs to be had.
Fixes https://github.com/AI-Hypercomputer/torchprime/issues/211.

Document how to configure the sharding

---

torchprime/data/dataset.py
torchprime/torch_xla_models/train.py
torchprime/utils/retry.py

Also add a retry logic on dataset and tokenizer download.
In the long run, we should cache those in GCS or somewhere, but this can
reduce CI flakiness in the meantime.

Factor out dataset logic to its own module and add retry

---

README.md
torchprime/torch_xla_models/configs/default.yaml

On older TPUs this will help the model not OOM.
All our optimized recipes explicitly override the batch size anyways so this should be fine.

Reduce default batch size to 4

---

.github/workflows/e2e_test.yml
pyproject.toml

Bump the pinned torch_xla nightly from Apr 26 to May 1 to pick up the profiler crash fix from libtpu.
When I first created the PR (first commit), the E2E test failed because `Llama 3.0 8B` exceeds the upper bound by 3ms, while `Llama 3.0 8B 2 slice` got faster than the lower bound by 210ms. I suspect the improvement of 210ms is due to improvements in libtpu, and the exceeding of 3ms is a result of noise, since the `Llama 3.0 8B` E2E test failed on `main` before my PR as well: https://github.com/AI-Hypercomputer/torchprime/actions/runs/14613075444/job/40995666070
As a result, I took more data points including runs from this PR and updated https://docs.google.com/spreadsheets/d/1VS_0tkmmUwT22F2eeqqIOuExiBwIIbqn58MXw3RMe7M/edit?gid=0#gid=0
I then updated the confidence intervals in …

torch_xla pin update to 0501

---

torchprime/torch_xla_models/README.md

After updating to the May 1 nightly, the profiling crash is finally fixed.
Log of a successful run: http://shortn/_LtdUSg95GX

Update Llama 3.1 405B recipe

---

.github/workflows/e2e_test.yml

After the pin update to May 1 nightly torch_xla, the Llama 2 slice training performance improved from 20s-30s to consistently around 4s. It's likely that there's new optimization landed in libtpu that stabilized the cross-slice network performance.
At this point all E2E tests have pretty tight confidence intervals which is nice!
I updated the spreadsheet [2] introduced in the initial E2E test PR [1] with new data since the May 1 pin update. For all other E2E tests except `Llama 3.0 8B 2 slice`, I used all historical data since Apr 4. For `Llama 3.0 8B 2 slice`, I used only data from May 1 onwards, which clearly has a different distribution. See linked spreadsheet.
[1]: https://github.com/AI-Hypercomputer/torchprime/pull/208
[2]: https://docs.google.com/spreadsheets/d/1VS_0tkmmUwT22F2eeqqIO …

Update E2E test bounds based on new data after pin update

---

pyproject.toml

Due to internal reasons, we have to move this library here: https://github.com/AI-Hypercomputer/aotc/tree/update-benchmark-db-writer/src/aotc/benchmark_db_writer

Update benchmark-db-writer again

---

.github/workflows/e2e_test.yml
pyproject.toml
torchprime/rope/rope.py
torchprime/torch_xla_models/llama/model.py
torchprime/torch_xla_models/llama4/__init__.py
torchprime/torch_xla_models/llama4/model.py
torchprime/torch_xla_models/llama4/model_original.py
torchprime/torch_xla_models/tests/test_llama.py
torchprime/torch_xla_models/tests/test_llama4.py
torchprime/torch_xla_models/tests/test_mixtral.py
torchprime/torch_xla_models/tests/test_remat_all.py

Had to update Llama3 unit test after bumping up transformers library as it explicitly calculates hidden dimension and also moved rotary_emb from DecodeLayer to model layer (where it should be). I'll update Llama3 implementation to reflect this.

Adding Llama4 text only implementation

---

.github/workflows/e2e_test.yml
torchprime/launcher/Dockerfile
torchprime/launcher/buildpush.py
torchprime/launcher/cli.py

This is a supporting change to https://github.com/AI-Hypercomputer/torchprime/issues/161. In order to test torchprime from PyTorch/XLA PRs, we will build a docker image from PyTorch/XLA side and trigger the E2E check defined here.
This PR teaches torchprime to override the pinned docker image when needed during the E2E test. This way we could build new images from PyTorch/XLA side and test them.

Run E2E tests with any base PyTorch/XLA docker image

---

.github/workflows/e2e_test.yml
e2e_testing/README.md
e2e_testing/step_time_bounds.yaml
e2e_testing/update_step_time.py
pyproject.toml
torchprime/launcher/benchmark_db_util.py
torchprime/launcher/cli.py

In this PR we replace the hardcoded step time bounds with a configuration file. We also add a script to automatically pull data from BigQuery to compute the step time bounds using the existing documented formula. Finally, we run the script with:
```sh
e2e_testing/update_step_time.py
```
to generate an accurate step time bound based on results from 1014 runs.
Now all the E2E tests are finally green again.

Compute E2E bounds from BigQuery data

---

README.md

This way the issue section can be used for issue tracking solely.
c.f. jax uses this model (https://github.com/jax-ml/jax/discussions)

Link to discussion panel

---

pyproject.toml
torchprime/launcher/thunk.py

Update PyTorch/XLA pin to Jun 6.
Initially this fails the multi-slice E2E test. I had to bisect the problem down to a specific libtpu version (https://github.com/AI-Hypercomputer/torchprime/pull/295) and found the bug in a libtpu commit and a workaround.
This PR adds a workaround for https://github.com/AI-Hypercomputer/torchprime/issues/300

Update PyTorch/XLA to 20250606

---

.github/workflows/e2e_test.yml
torchprime/torch_xla_models/model/base_causal_lm.py
torchprime/torch_xla_models/model/model_utils.py
torchprime/torch_xla_models/model_rewriting/auto_trace.py
torchprime/torch_xla_models/model_rewriting/sharding_initialization.py
torchprime/torch_xla_models/tests/test_auto_trace.py
torchprime/torch_xla_models/train.py
torchprime/torch_xla_models/trainer/base_trainer.py

LLMs use a lot of linear layers and it is nice to disambiguate them on the profile.
Before this PR:
After this PR:
Note the presence of `o_proj`, `up_proj`, `down_proj`, `gate_proj`, etc.
Now we'll actually know what a specific einsum is doing.

Add `xp.Trace` profile scopes to all `nn.Linear` layers

---

.github/workflows/e2e_test.yml
docs/metrics.md
torchprime/tests/test_profiling_utils.py
torchprime/torch_xla_models/README.md
torchprime/torch_xla_models/configs/default.yaml
torchprime/torch_xla_models/tests/test_trainer.py
torchprime/torch_xla_models/trainer/base_trainer.py
torchprime/utils/profiling.py

Fixing https://github.com/AI-Hypercomputer/torchprime/issues/263
- update `xp.trace_detached` with `start_trace` and `stop_trace`
- default profile_start_step to 3 and profile_end_step to null
- add utility ensure_profile_end_step to compute default end step
- call utility during trainer initialization
- test ensure_profile_end_step

Update profiler defaults

---

torchprime/experimental/torchax_models/run.py
torchprime/experimental/torchax_models/splash_attn.py
torchprime/tests/test_parallelism_utils.py
torchprime/utils/parallelism_utils.py

1. Add reorder_sequence function to rearrange q/k/v sequences and reorder it back
2. Add Loadbalanced casual mask 
3. Allow passing mask in the splash attention kernel for torchax
4. Add tests for these functions
Next PR will be adding sharding support for context parallelism
Below is a brief write up of how this supports CP:
You could read some context here: https://insujang.github.io/2024-09-20/introducing-context-parallelism/

Add basic context parallelism: 1/3

---

.github/workflows/reusable_e2e_check.yml

Fix two problems:
- If there were too many workloads queued, getting pod name will fail [1]
- If the workload already finished before the `kubectl wait` is run, then `kubectl wait` will hang [2]
[1]: https://github.com/AI-Hypercomputer/torchprime/actions/runs/15355212312/job/43213161310
[2]: https://github.com/AI-Hypercomputer/torchprime/actions/runs/15647679573/job/44089703686?pr=284

Fix race conditions in waiting logic

---

.github/workflows/e2e_test.yml

If not provided target_loss, seems e2e workflow will not run. Fixing it but defaulting to 0 if target_loss not provided.

Fix e2e test issue when target_loss is not provided

---

torchprime/torch_xla_models/configs/model/llama-4-text-only-scout-17b-16e.yaml
torchprime/torch_xla_models/configs/model/sharding/llama4-fsdp-tp-ep.yaml
torchprime/torch_xla_models/configs/model/sharding/llama4-fsdp-tp.yaml
torchprime/torch_xla_models/configs/model/sharding/llama4-fsdp.yaml
torchprime/torch_xla_models/model/llama4/model.py
torchprime/torch_xla_models/tests/test_llama4.py

Was able to run it as:
tp run --name alekseyv-llama-4-18-ep \
torchprime/torch_xla_models/train.py \
model=llama-4-text-only-scout-17b-16e \
task.global_batch_size=256 \
ici_mesh.fsdp=16 \
ici_mesh.data=1 \
ici_mesh.expert=16 \
dataset.block_size=512 \
model/sharding=llama4-fsdp-tp-ep
Performance is still not great

adding expert parallelism to Llama4

---

torchprime/data/dataset.py
torchprime/data/sft_dataset.py
torchprime/launcher/cli.py
torchprime/launcher/save_hf_assets_to_gcs.py
torchprime/torch_xla_models/configs/default.yaml

- created tp command to save raw/processed dataset in gcs
- enabled make_train_dataset to load preprocessed dataset from gcs bucket
https://github.com/AI-Hypercomputer/torchprime/issues/115
https://github.com/AI-Hypercomputer/torchprime/issues/262
Saving preprocessed dataset:
```
tp save-hf-dataset     --repo-id wikitext     --config-name wikitext-103-raw-v1     --gcs-path gs://bucketname/datasets/wikitext-preprocessed     --preprocess     --split train     --tokenizer-repo-id meta-llama/Meta-Llama-3-8B     --block-size 1024     --temp-dir /tmp
```
Tested with wikitext data on llama-3-8B

Load Huggingface dataset from a GCS cache

---

torchprime/launcher/test_run_model.py

When running test_run_model on TPU, it was hanging indefinitely. I realized that the hanging was occuring when testing the torchax part and when I divide them to two separate test, hanging stopped.
I am not exactly sure why this is happening but my best guess is some conflict between initializing backend for TPU. If anyone knows better explanation, please let me know.
Environment:
- TPU VM: v4-8
- Python 3.11

Fix test_run_model from hanging when running on TPU

---

torchprime/launcher/run_model.py

When running unit test on TPU, some of there were hanging: https://github.com/AI-Hypercomputer/torchprime/issues/375
Seems like the hanging for some test only happens when `test_run_model.py` was ran before (could be some deadlock happening to access libtpu. It was fixed by importing torchax at function level.

Fix TPU unit test hanging
